"""Add Thread model

Revision ID: 2560e6f4f897
Revises: 17d7647a3990
Create Date: 2025-05-28 23:17:01.165266

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2560e6f4f897'
down_revision: Union[str, None] = '17d7647a3990'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    # Buat tabel threads
    op.create_table('threads',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('title', sa.String(length=255), nullable=False),
        sa.Column('content', sa.Text(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['users.id']),
        sa.PrimaryKeyConstraint('id')
    )
    
    # Tambahkan kolom content dengan default sementara
    op.add_column('comments', sa.Column('content', sa.Text(), nullable=True, server_default=''))
    op.alter_column('comments', 'content', nullable=False, server_default=None)
    
    # Tambahkan kolom thread_id sebagai nullable
    op.add_column('comments', sa.Column('thread_id', sa.Integer(), nullable=True))
    
    # Jangan isi dengan 0, biarkan NULL untuk komentar lama
    # op.execute("UPDATE comments SET thread_id = 0 WHERE thread_id IS NULL")  # Hapus atau jangan gunakan
    
    # Buat foreign key dengan kolom nullable
    op.drop_constraint('fk_comments_article_id_articles', 'comments', type_='foreignkey')
    op.create_foreign_key('fk_comments_thread_id_threads', 'comments', 'threads', ['thread_id'], ['id'])
    
    # Hapus kolom article_id dan text lama
    op.drop_column('comments', 'article_id')
    op.drop_column('comments', 'text')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('text', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('comments', sa.Column('article_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(op.f('fk_comments_thread_id_threads'), 'comments', type_='foreignkey')
    op.create_foreign_key('fk_comments_article_id_articles', 'comments', 'articles', ['article_id'], ['id'])
    op.drop_column('comments', 'thread_id')
    op.drop_column('comments', 'content')
    op.drop_table('threads')
    # ### end Alembic commands ###
