"""Create thread_tag table

Revision ID: 87d1fc16eafe
Revises: bafb8206ad9f
Create Date: 2025-05-29 07:37:33.446724

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87d1fc16eafe'
down_revision: Union[str, None] = 'bafb8206ad9f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('thread_tag',
    sa.Column('thread_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], name=op.f('fk_thread_tag_tag_id_tags')),
    sa.ForeignKeyConstraint(['thread_id'], ['threads.id'], name=op.f('fk_thread_tag_thread_id_threads')),
    sa.PrimaryKeyConstraint('thread_id', 'tag_id', name=op.f('pk_thread_tag'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('thread_tag')
    # ### end Alembic commands ###
