"""Add article_id back to comments

Revision ID: c95845522d4e
Revises: 2560e6f4f897
Create Date: 2025-05-28 23:50:07.105201

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c95845522d4e'
down_revision: Union[str, None] = '2560e6f4f897'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('article_id', sa.Integer(), nullable=True))
    op.create_foreign_key(op.f('fk_comments_article_id_articles'), 'comments', 'articles', ['article_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_comments_article_id_articles'), 'comments', type_='foreignkey')
    op.drop_column('comments', 'article_id')
    # ### end Alembic commands ###
